global:
  domain: argocd.fabiobartoli.com.br

configs:
  params:
    server.insecure: "false"

  cm:
    url: https://argocd.fabiobartoli.com.br

  accounts:
    linuxtips: login

  secret:
    extra:
      accounts.linuxtips.password: eolhasoein

  rbac:
    policy.default: role:readonly
    policy.csv: |
      p, role:admin, *, *, */*, allow
      g, linuxtips, role:admin

server:
  service:
    type: ClusterIP

  ingress:
    enabled: false

  # Configuração de recursos para o ArgoCD
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

controller:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

applicationSet:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
